version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    command: sh -c "sleep 5 && src/manage.py migrate && src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db